# Generated by Django 6.0 on 2026-03-03 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_critico',
            field=models.PositiveIntegerField(default=5, help_text='Nivel mínimo para alertas'),
        ),
        migrations.CreateModel(
            name='MovimientoKardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('INICIAL', 'Carga Inicial de Stock'), ('ENTRADA_COMPRA', 'Entrada por Compra'), ('SALIDA_VENTA', 'Salida por Venta'), ('DEVOLUCION', 'Devolución (Venta Anulada)'), ('AJUSTE_POSITIVO', 'Ajuste Manual (Sobrante)'), ('AJUSTE_NEGATIVO', 'Ajuste Manual (Merma/Pérdida)')], max_length=30)),
                ('cantidad', models.PositiveIntegerField()),
                ('stock_anterior', models.PositiveIntegerField()),
                ('stock_nuevo', models.PositiveIntegerField()),
                ('motivo', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_kardex', to='modulo_principal.producto')),
                ('usuario', models.ForeignKey(help_text='Quién realizó el movimiento', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Kardex',
                'verbose_name_plural': 'Movimientos de Kardex',
                'ordering': ['-fecha'],
            },
        ),
    ]
